spring.application.name=demo padma

spring.datasource.url= jdbc
spring.datasource.username=
spring.datasource.password=
spring.jpa.show.sql=true //es bueno para desarrollo pero no sirve para produccion

##Hibernate properties
#The sql dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update //update es bueno para desarrollo y no sirve para produccion, validate es bueno para produccion