spring.application.name=demo padma

spring.datasource.url= jdbc:mariadb://129.146.249.153:3313/padma?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC    
spring.datasource.username=root
spring.datasource.password=UFPS2025
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.show.sql=true
##//es bueno para desarrollo pero no sirve para produccion


##Esto es para el navegador, para css, SOLO DESARROLLO: 
# Desactivar caché de plantillas Thymeleaf
spring.thymeleaf.cache=false

# Desactivar caché de CSS/JS/imágenes
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

#live reload
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.devtools.livereload.port=35729


##Hibernate properties
#The sql dialect makes Hibernate generate better SQL for the chosen database
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect

#Hibernate ddl auto (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update
##update es bueno para desarrollo y no sirve para produccion, validate es bueno para produccion

##JACKSON JSON CONFIGURATIONS
spring.jackson.deserialization.fail-on-null-for-primitives=false
spring.jackson.deserialization.fail-on-unknown-properties=false

##additional
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true